require 'rake'
require 'rake/rdoctask'
require 'rake/testtask'

task :default => "test"

namespace :test do
  desc "Test all classes"
  Rake::TestTask.new(:all) do |t|
    t.libs << "test"
    t.pattern = 'test/*_test.rb'
    t.verbose = true
  end 
end

desc "Run all the unit tests"
task :test do
  Rake::Task["test:all"].invoke
end

desc 'Generate documentation.'
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'jump'
  rdoc.options << '--line-numbers' << "--main" << "README.rdoc"
  rdoc.rdoc_files.include('README.rdoc')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name        = %q{jump}
    gem.summary     = %q{A bookmarking system for the bash shell}
    gem.description = %q{Jump is a tool that allows you to quickly change
                       directories in the bash shell using bookmarks.
                       Thanks to Jump, you won't have to type those long paths anymore.

                       Jump was inspired by go-tool by ActiveState
                       (http://code.google.com/p/go-tool/).}

    gem.files        = FileList['[A-Z]*', 'lib/**/*.rb', 'test/**/*.rb']
    gem.require_path = 'lib'
    gem.bindir = 'bin'
    gem.executables = ['jump-bin']
    gem.test_files   = Dir[*['test/**/*_test.rb']]

    gem.has_rdoc         = true
    gem.extra_rdoc_files = ["README.rdoc"]
    gem.rdoc_options = ['--line-numbers', "--main", "README.rdoc"]

    gem.authors = ["Flavio Castelli", "Giuseppe Capizzi"]
    gem.email   = %w(flavio@castelli.name gcapizzi@gmail.com)
    gem.homepage = "http://github.com/gcapizzi/jump"

    gem.add_dependency "terminal-table"
    gem.add_development_dependency "fakefs"

    gem.platform = Gem::Platform::RUBY
    gem.post_install_message = File.read('POST_INSTALL.txt')
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler not available. Install it with: gem install jeweler"
end

desc "Clean files generated by rake tasks"
task :clobber => [:clobber_rdoc]
